# Generated by Django 5.1.6 on 2025-04-21 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(choices=[('IT & Networking', 'IT & Networking'), ('Repair & Maintenance', 'Repair & Maintenance'), ('Design & Multimedia', 'Design & Multimedia'), ('Accounting & Finance', 'Accounting & Finance'), ('Programming', 'Programming'), ('Web & App Development', 'Web & App Development'), ('English Language & Exam Prep', 'English Language & Exam Prep'), ('Marketing & Freelancing', 'Marketing & Freelancing'), ('Engineering & Robotics', 'Engineering & Robotics'), ('General Computer Skills', 'General Computer Skills')], max_length=200, null=True)),
                ('course', models.CharField(choices=[('Mobile Repairing Course', 'Mobile Repairing Course'), ('Laptop Repairing', 'Laptop Repairing'), ('Computer Hardware Engineering', 'Computer Hardware Engineering'), ('MCSE-MCITP-Networking', 'MCSE-MCITP-Networking'), ('CCNA-CCNP', 'CCNA-CCNP'), ('CCTV', 'CCTV'), ('AutoCAD 20 & 30', 'AutoCAD 20 & 30'), ('3D Max', '3D Max'), ('Peach Tree, Quick Book, Tally', 'Peach Tree, Quick Book, Tally'), ('Web Designing & Development', 'Web Designing & Development'), ('MERN Stack', 'MERN Stack'), ('Android Application Course', 'Android Application Course'), ('Cloud Computing', 'Cloud Computing'), ('Bobotics', 'Bobotics'), ('Full Stack Graphic Designing', 'Full Stack Graphic Designing'), ('Adobe Illustrator', 'Adobe Illustrator'), ('Adobe Premiere Pro', 'Adobe Premiere Pro'), ('Spoken English', 'Spoken English'), ('IELTS', 'IELTS'), ('AT (English Spouse Visa Course)', 'AT (English Spouse Visa Course)'), ('Computer Course for Beginners', 'Computer Course for Beginners'), ('Computer Programming', 'Computer Programming'), ('Visual Basic', 'Visual Basic'), ('C++', 'C++'), ('Java', 'Java'), ('Digital Marketing', 'Digital Marketing'), ('Freelancing Course', 'Freelancing Course'), ('SEO (Search Engine Optimization)', 'SEO (Search Engine Optimization)')], max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
