# Generated by Django 5.1.6 on 2025-04-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('course_name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('staff_name', models.CharField(max_length=200)),
                ('staff_email', models.EmailField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
