# Generated by Django 5.1.6 on 2025-04-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_exam_alter_course_created_at_alter_course_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='created_at',
        ),
    ]
