# Generated by Django 5.1.6 on 2025-06-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_course_course_name_course_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
